[package]
name = "cli"
description = "ninty-router binary"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
embed-web = ["server/embed-web"]

[[bin]]
name = "ninty-router"
path = "src/main.rs"

[dependencies]
ninty-core = { path = "../core" }
server = { path = "../server" }
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
clap = { version = "4", features = ["derive"] }
